name: API Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Sanitize & Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - run: yarn lint
    - run: npx lerna run build --stream
    - run: yarn test

  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: yarn

    - name: Build packages
      run: npx lerna run build --stream

    - run: yarn versions:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
